name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
           if [ ! -d "$HOME/devops-course-project/.git" ]; then
              echo "Cloning repo..."
              git clone https://github.com/${{ github.repository }}.git ~/devops-course-project
            else
              echo "Repo already exists, pulling latest..."
            fi

            cd ~/devops-course-project
            chmod +x scripts/deploy.sh
            bash scripts/deploy.sh